"use strict";
/**
 * 2026 版综测规则字典（大外校发〔2026〕7号 + 软件学院研判）
 * 所有分值为"默认/封顶/认定条件"，复审时可按规则核定 grantedScore；
 * 批次激活后进 BatchRule 快照，改字典不影响进行中批次。
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CERT_LANG_ENTRIES = exports.COMPETITION_B_MUNICIPAL = exports.COMPETITION_B_PROVINCIAL = exports.COMPETITION_B_NATIONAL = exports.COMPETITION_A = exports.RULES_2026 = void 0;
exports.RULES_2026 = [
    // ============ 品德行为表现（基础 9 分，总分封顶 15） ============
    {
        code: 'MORAL_BLOOD',
        category: 'MORAL',
        name: '献血',
        description: '考评学期参加【学校统一组织的】献血活动（2026 新版：仅学校统一组织的当学期献血计分），凭献血证 +1',
        detailSchema: [
            { field: 'date', label: '献血日期', type: 'date', required: true },
            { field: 'organizer', label: '组织单位（须为学校统一组织）', type: 'string', required: true, placeholder: '如：校医院/学生处统一组织' },
        ],
        defaultScore: 1,
        caps: { perTermMax: 1 },
        evidence: [{ label: '献血证扫描件', accept: ['pdf', 'jpg', 'jpeg', 'png', 'webp'], required: true }],
        exportSlot: 'MORAL_BLOOD',
    },
    {
        code: 'MORAL_HONOR',
        category: 'MORAL',
        name: '优秀学生教官/国旗班/参军入伍',
        description: '优秀学生教官 +2；国旗班成员 +2；兼具国旗班与优秀学生教官 +3；参军入伍退役复学 +3（立三等功及以上另加分）',
        detailSchema: [
            {
                field: 'honorType',
                label: '类型',
                type: 'select',
                required: true,
                options: [
                    { label: '国旗班成员', value: 'FLAG_TEAM', score: 2 },
                    { label: '优秀学生教官', value: 'EXCELLENT_INSTRUCTOR', score: 2 },
                    { label: '兼具国旗班与优秀学生教官', value: 'BOTH', score: 3 },
                    { label: '参军入伍退役复学', value: 'VETERAN', score: 3 },
                    { label: '入伍期间荣立三等功及以上', value: 'MERIT_3RD', score: 1 },
                ],
                scoreHint: true,
            },
        ],
        defaultScore: null,
        caps: { perTermMax: 3 },
        evidence: [{ label: '荣誉证书/退役证明', accept: ['pdf', 'jpg', 'jpeg', 'png', 'webp'], required: true }],
        exportSlot: 'MORAL_HONOR',
    },
    {
        code: 'MORAL_PEER_TUTOR',
        category: 'MORAL',
        name: '优秀班导生',
        description: '学院研判：获得"优秀班导生"荣誉称号的所在学期末 +1.5 品德分',
        detailSchema: [{ field: 'term', label: '获评学期', type: 'string', required: true, placeholder: '如 2025-2026-1' }],
        defaultScore: 1.5,
        caps: { perTermMax: 1.5 },
        evidence: [{ label: '荣誉证书', accept: ['pdf', 'jpg', 'jpeg', 'png', 'webp'], required: true }],
        exportSlot: 'MORAL_PEER_TUTOR',
    },
    {
        code: 'MORAL_DORM',
        category: 'MORAL',
        name: '寝室卫生检查',
        description: '学期平均分≥90：成员 +0.8、寝室长 +1；≤60：成员 −1、寝室长 −1.2（扣分项由复审录入负分）',
        detailSchema: [
            {
                field: 'dormResult',
                label: '检查结果',
                type: 'select',
                required: true,
                options: [
                    { label: '学期均分≥90（成员）', value: 'GOOD_MEMBER', score: 0.8 },
                    { label: '学期均分≥90（寝室长）', value: 'GOOD_LEADER', score: 1 },
                    { label: '学期均分≤60（成员）', value: 'BAD_MEMBER', score: -1 },
                    { label: '学期均分≤60（寝室长）', value: 'BAD_LEADER', score: -1.2 },
                ],
                scoreHint: true,
            },
            { field: 'dormNo', label: '寝室号', type: 'string', required: true },
        ],
        defaultScore: null,
        evidence: [{ label: '检查结果证明（如需）', accept: ['pdf', 'jpg', 'jpeg', 'png', 'webp'], required: false }],
        exportSlot: 'MORAL_DORM',
    },
    {
        code: 'MORAL_SELFSTUDY',
        category: 'MORAL',
        name: '早晚自习考勤',
        description: '未请假旷早晚自习一节 −0.5；迟到早退一次 −0.1（负分由复审/班委按记录录入）',
        detailSchema: [
            { field: 'absentCount', label: '旷自习节数', type: 'number', required: false },
            { field: 'lateCount', label: '迟到/早退次数', type: 'number', required: false },
        ],
        defaultScore: null,
        evidence: [{ label: '考勤记录', accept: ['pdf', 'jpg', 'jpeg', 'png', 'webp'], required: false }],
        exportSlot: 'MORAL_SELFSTUDY',
    },
    {
        code: 'MORAL_PRACTICE_VOLUNTEER',
        category: 'MORAL',
        name: '社会实践/志愿服务',
        description: '学院研判：院级/校级活动完成任务 +1；市级及以上活动或校级活动主要组织者 +1.5；省级及以上活动或获校级及以上表彰/突出成果 +2。同学期多次参加按最高档计、不累计；须提交制式材料（附件1）',
        detailSchema: [
            {
                field: 'tier',
                label: '活动档次',
                type: 'select',
                required: true,
                options: [
                    { label: '院级/校级活动并完成任务', value: 'T1', score: 1 },
                    { label: '市级及以上活动，或校级活动主要组织者', value: 'T2', score: 1.5 },
                    { label: '省级及以上活动，或获校级及以上表彰/突出成果', value: 'T3', score: 2 },
                ],
                scoreHint: true,
            },
            { field: 'activityName', label: '活动名称', type: 'string', required: true },
            { field: 'organizer', label: '组织单位', type: 'string', required: true },
            { field: 'date', label: '活动日期', type: 'date', required: true },
            { field: 'isOrganizer', label: '是否主要组织者', type: 'boolean' },
        ],
        defaultScore: null,
        caps: { takeHighest: true, perTermMax: 2 },
        evidence: [
            { label: '社会实践表（盖章扫描件）', accept: ['pdf'], required: false },
            { label: '志愿服务证书', accept: ['pdf', 'jpg', 'jpeg', 'png', 'webp'], required: false },
        ],
        exportSlot: 'MORAL_PRACTICE_VOLUNTEER',
    },
    {
        code: 'MORAL_CLASSROOM',
        category: 'MORAL',
        name: '教室卫生检查',
        description: '学期平均分≤60：全班 −1、生活委员 −1.2（负分由复审录入）',
        detailSchema: [
            {
                field: 'classroomResult',
                label: '检查结果',
                type: 'select',
                required: true,
                options: [
                    { label: '学期均分≤60（成员）', value: 'BAD_MEMBER', score: -1 },
                    { label: '学期均分≤60（生活委员）', value: 'BAD_LEADER', score: -1.2 },
                ],
                scoreHint: true,
            },
        ],
        defaultScore: null,
        evidence: [],
        exportSlot: 'MORAL_CLASSROOM',
    },
    {
        code: 'MORAL_OTHER',
        category: 'MORAL',
        name: '其他品德奖扣分',
        description: '合理化建议被采用 +1~2；配合院校工作 +0.5~1；心理危机上报 +2；政治理论学习 0.1~3；见义勇为等表彰 1~6；处分扣分：通报批评 −0.5/警告 −1/严重警告 −2/记过 −3/留校察看 −4；旷课一节 −0.8；扰乱课堂 −1/次；欠费 −1~−2；漏寝外宿 −1/次',
        detailSchema: [
            { field: 'item', label: '事项', type: 'string', required: true, placeholder: '如：拾金不昧获校级表彰 / 记过处分' },
            { field: 'date', label: '日期', type: 'date', required: false },
            { field: 'note', label: '情况说明', type: 'textarea', required: false },
        ],
        defaultScore: null,
        evidence: [{ label: '佐证材料', accept: ['pdf', 'jpg', 'jpeg', 'png', 'webp'], required: false }],
        exportSlot: 'MORAL_OTHER',
    },
    // ============ 学业表现（基础 = 加权×75%，总分封顶 75） ============
    {
        code: 'ACA_COMPETITION',
        category: 'ACADEMIC',
        name: '专业相关学术竞赛',
        description: '第一名：国家级 +3 / 省部级 +2 / 市级 +1；集体项目减半；第 2 名至最后一名递减 0.2（集体递减 0.1）；优秀奖按二等奖计；同一活动只计最高分，多项可累计。【必须在教务处当年校外赛事认定目录中，未列入不予加分；辽宁省教育厅主办的创新创业类竞赛直接认定省级】',
        detailSchema: [
            { field: 'competitionName', label: '竞赛全称', type: 'string', required: true, placeholder: '须与认定目录名称一致' },
            { field: 'level', label: '级别', type: 'select', required: true, options: [
                    { label: '国家级', value: 'NATIONAL', score: 3 },
                    { label: '省部级', value: 'PROVINCIAL', score: 2 },
                    { label: '市级', value: 'MUNICIPAL', score: 1 },
                ], scoreHint: true },
            { field: 'rank', label: '名次/奖级', type: 'string', required: true, placeholder: '如：一等奖/第 1 名/优秀奖' },
            { field: 'isTeam', label: '是否集体项目', type: 'boolean' },
            { field: 'date', label: '获奖日期', type: 'date', required: true },
        ],
        defaultScore: null,
        levelScoreMap: { NATIONAL: 3, PROVINCIAL: 2, MUNICIPAL: 1 },
        caps: { takeHighest: false },
        whitelistType: 'COMPETITION_CATALOG',
        evidence: [{ label: '获奖证书', accept: ['pdf', 'jpg', 'jpeg', 'png', 'webp'], required: true }],
        exportSlot: 'ACA_COMPETITION',
    },
    {
        code: 'ACA_CERT',
        category: 'ACADEMIC',
        name: '语言/职业技能证书',
        description: '学院研判：CET-4≥425、CET-6≥425、JLPT N2 及以上、TEM-4/TEM-8 合格 → 证书下发当学期 +1；同一证书仅认定一次、同一等级四年内仅一次、不跨学期、逾期视为放弃。教育部等部委颁布的职业/技能等级证书 +1（仅可申报一次）。【驾驶证、普通话等新版已删除，不予加分】',
        detailSchema: [
            { field: 'certType', label: '证书类型', type: 'select', required: true, options: [
                    { label: '大学英语四级 CET-4（≥425）', value: 'CET4', score: 1 },
                    { label: '大学英语六级 CET-6（≥425）', value: 'CET6', score: 1 },
                    { label: '日本语能力测试 JLPT N2', value: 'JLPT_N2', score: 1 },
                    { label: '日本语能力测试 JLPT N1', value: 'JLPT_N1', score: 1 },
                    { label: '英语专业四级 TEM-4（合格）', value: 'TEM4', score: 1 },
                    { label: '英语专业八级 TEM-8（合格）', value: 'TEM8', score: 1 },
                    { label: '部委职业/技能等级证书', value: 'VOCATIONAL', score: 1 },
                ], scoreHint: true },
            { field: 'certNo', label: '证书编号/准考证号', type: 'string', required: true },
            { field: 'issueDate', label: '成绩/证书下发日期', type: 'date', required: true, placeholder: '须为当学期下发' },
            { field: 'score', label: '分数（CET 类必填）', type: 'number', required: false },
        ],
        defaultScore: 1,
        caps: { perTermMax: null, dedupeScope: 'CERT_NO' },
        whitelistType: 'CERT_LANG',
        evidence: [{ label: '电子成绩单/证书扫描件', accept: ['pdf', 'jpg', 'jpeg', 'png', 'webp'], required: true, hint: '四六级请上传官网下载的电子成绩报告单' }],
        exportSlot: 'ACA_CERT',
    },
    {
        code: 'ACA_RESEARCH',
        category: 'ACADEMIC',
        name: '科研（论文/课题/专利/软著）',
        description: '核心刊物 5/3/2/1；一般刊物 3/2/1/0.8；论文集 2/1/0.8/0.6；课题：国家级 5/4/3.5/3、省 4/3/2.5/2、市 3/2/1.5/1.2、校 2/1/0.8/0.6；发明专利 5/4/3.5/3；软著 1/0.8/0.6（学院研判：同学期最多认定 2 项、累计 ≤2 分、同年当学期仅一次、转让买卖取得不认定，须提供登记证书+源代码或运行演示）',
        detailSchema: [
            { field: 'researchType', label: '类型', type: 'select', required: true, options: [
                    { label: '学术论文', value: 'PAPER' },
                    { label: '科研课题立项', value: 'PROJECT' },
                    { label: '发明专利', value: 'PATENT' },
                    { label: '计算机软件著作权', value: 'SOFTWARE_COPYRIGHT' },
                ] },
            { field: 'level', label: '级别（课题/刊物）', type: 'select', required: false, options: [
                    { label: '核心刊物/国家级', value: 'NATIONAL' },
                    { label: '一般刊物/省部级', value: 'PROVINCIAL' },
                    { label: '市级', value: 'MUNICIPAL' },
                    { label: '校级/论文集', value: 'UNIVERSITY' },
                ] },
            { field: 'role', label: '本人角色', type: 'select', required: true, options: [
                    { label: '主持人/第一作者', value: 'HOST' },
                    { label: '第一参与人', value: 'P1' },
                    { label: '第二参与人', value: 'P2' },
                    { label: '第三参与人', value: 'P3' },
                ] },
            { field: 'title', label: '论文/课题/软著名称', type: 'string', required: true },
            { field: 'certNo', label: '登记号/立项号', type: 'string', required: true },
            { field: 'isOriginal', label: '本人确认为原始取得（非转让买卖）', type: 'boolean' },
        ],
        defaultScore: null,
        levelScoreMap: { NATIONAL: 5, PROVINCIAL: 4, MUNICIPAL: 3, UNIVERSITY: 2 },
        caps: { itemCountMax: 2, perTermMax: 2, dedupeScope: 'CERT_NO' },
        evidence: [
            { label: '登记证书/立项书/见刊页', accept: ['pdf'], required: true },
            { label: '软著须附源代码或运行演示', accept: ['pdf', 'jpg', 'jpeg', 'png', 'webp'], required: false },
        ],
        exportSlot: 'ACA_RESEARCH',
    },
    // ============ 文体表现（基础 3 分，总分封顶 10） ============
    {
        code: 'SPORTS_CADRE',
        category: 'SPORTS',
        name: '学生干部',
        description: '主席团/分团委副书记 3.0；部长、年级长、团支书、班长 2.0；副部长、学习委员 1.5；部员、班委 1.0；职能部门 A 级 1.5/B 级 1.0/C 级 0.5。身兼多职按最高职务计、不累计（≤3 分）。【只提交最高一项证明，班委加分证明不用提交】',
        detailSchema: [
            { field: 'position', label: '职务', type: 'select', required: true, options: [
                    { label: '校/院学生组织主席团成员、分团委副书记', value: 'PRESIDIUM', score: 3 },
                    { label: '部长、年级长、班级团支书、班长', value: 'MINISTER', score: 2 },
                    { label: '副部长、班级学习委员', value: 'VICE_MINISTER', score: 1.5 },
                    { label: '部员、班级其他班委', value: 'MEMBER', score: 1 },
                    { label: '职能部门 A 级（≤10%）', value: 'DEPT_A', score: 1.5 },
                    { label: '职能部门 B 级（≤20%）', value: 'DEPT_B', score: 1 },
                    { label: '职能部门 C 级（≤70%）', value: 'DEPT_C', score: 0.5 },
                ], scoreHint: true },
            { field: 'org', label: '任职单位', type: 'string', required: true },
            { field: 'term', label: '任职学期', type: 'string', required: true },
        ],
        defaultScore: null,
        caps: { takeHighest: true, perTermMax: 3 },
        evidence: [{ label: '任职证明（仅最高职务一项）', accept: ['pdf', 'jpg', 'jpeg', 'png', 'webp'], required: false, hint: '班委加分证明不用提交' }],
        exportSlot: 'SPORTS_CADRE',
    },
    {
        code: 'SPORTS_EVENT',
        category: 'SPORTS',
        name: '非专业领域文体实践（文艺/体育/社会实践）',
        description: '正式参加：国家级 +1.5 / 省部级 +1.2 / 市级 +1；获市级以上奖励另加：第一名国家级 +1 / 省 +0.8 / 市 +0.6，第 2 名起递减 0.2、集体递减 0.1、集体减半；优秀奖按二等奖计；同一活动只计最高分。【须为学校或学院统一组织的活动】',
        detailSchema: [
            { field: 'activityName', label: '活动全称', type: 'string', required: true },
            { field: 'organizer', label: '组织单位（须校/院统一组织）', type: 'string', required: true },
            { field: 'level', label: '级别', type: 'select', required: true, options: [
                    { label: '国家级', value: 'NATIONAL', score: 1.5 },
                    { label: '省部级', value: 'PROVINCIAL', score: 1.2 },
                    { label: '市级', value: 'MUNICIPAL', score: 1 },
                ], scoreHint: true },
            { field: 'award', label: '获奖情况', type: 'string', required: false, placeholder: '如：第一名/第二名/未获奖' },
            { field: 'isTeam', label: '是否集体项目', type: 'boolean' },
            { field: 'date', label: '活动日期', type: 'date', required: true },
        ],
        defaultScore: null,
        levelScoreMap: { NATIONAL: 1.5, PROVINCIAL: 1.2, MUNICIPAL: 1 },
        caps: { takeHighest: false },
        evidence: [{ label: '参赛/获奖证明', accept: ['pdf', 'jpg', 'jpeg', 'png', 'webp'], required: true }],
        exportSlot: 'SPORTS_EVENT',
    },
    {
        code: 'SPORTS_CAMPUS',
        category: 'SPORTS',
        name: '校园文化活动',
        description: '正式参加 +0.2；获奖另加：校级第一名 +0.5/第二 +0.4/第三 +0.3/第三以下 +0.2；院级第一 +0.4/第二 +0.3/第三 +0.2/第三以下 +0.1。集体项目个人获奖减半、基础参加分不减半',
        detailSchema: [
            { field: 'activityName', label: '活动全称', type: 'string', required: true },
            { field: 'level', label: '级别', type: 'select', required: true, options: [
                    { label: '校级', value: 'UNIVERSITY' },
                    { label: '院级', value: 'COLLEGE' },
                ] },
            { field: 'award', label: '获奖情况', type: 'select', required: false, options: [
                    { label: '仅参加（无获奖）', value: 'NONE', score: 0.2 },
                    { label: '第一名', value: 'R1' },
                    { label: '第二名', value: 'R2' },
                    { label: '第三名', value: 'R3' },
                    { label: '第三名以下', value: 'R4' },
                ], scoreHint: true },
            { field: 'isTeam', label: '是否集体项目', type: 'boolean' },
            { field: 'date', label: '活动日期', type: 'date', required: true },
        ],
        defaultScore: 0.2,
        caps: { takeHighest: false },
        evidence: [{ label: '参加/获奖证明', accept: ['pdf', 'jpg', 'jpeg', 'png', 'webp'], required: true }],
        exportSlot: 'SPORTS_CAMPUS',
    },
    {
        code: 'SPORTS_JOURNAL',
        category: 'SPORTS',
        name: '非专业期刊/媒体投稿',
        description: '全国性正式刊号刊物每篇 +1（消息类累计 ≤2）；省市级 +0.5（累计 ≤1）；官方通讯社新闻网站：副局级及以上每篇 +1（≤2）、正处级 +0.5（≤1）；校内备案刊物/平台每篇 +0.3；同一文章只计最高分',
        detailSchema: [
            { field: 'platform', label: '发表平台类型', type: 'select', required: true, options: [
                    { label: '全国性正式刊号刊物', value: 'NATIONAL_JOURNAL', score: 1 },
                    { label: '省市级正式刊号刊物', value: 'PROV_JOURNAL', score: 0.5 },
                    { label: '官方新闻网站（副局级及以上）', value: 'NEWS_HIGH', score: 1 },
                    { label: '官方新闻网站（正处级）', value: 'NEWS_MID', score: 0.5 },
                    { label: '校内备案刊物/平台', value: 'CAMPUS', score: 0.3 },
                ], scoreHint: true },
            { field: 'title', label: '文章标题', type: 'string', required: true },
            { field: 'mediaName', label: '刊物/媒体名称', type: 'string', required: true },
            { field: 'publishDate', label: '发表日期', type: 'date', required: true },
        ],
        defaultScore: null,
        caps: { takeHighest: true },
        evidence: [{ label: '发表页面/刊物扫描件（须署名大连外国语大学）', accept: ['pdf', 'jpg', 'jpeg', 'png', 'webp'], required: true }],
        exportSlot: 'SPORTS_JOURNAL',
    },
];
// ============ 竞赛白名单（2026 教务处认定目录） ============
exports.COMPETITION_A = [
    '中国国际"互联网+"大学生创新创业大赛',
    '"挑战杯"全国大学生课外学术科技作品竞赛',
    '"挑战杯"中国大学生创业计划大赛',
    '"创青春"全国大学生创业计划大赛',
    '"外研社杯"全国大学生英语演讲比赛',
    'ACM-ICPC 国际大学生程序设计竞赛',
    '全国大学生电子设计竞赛',
    '全国大学生广告艺术大赛',
    '全国大学生物流设计大赛',
    '全国大学生市场调查与分析大赛',
    '全国大学生电子商务"创新、创意及创业"挑战赛',
    '两岸新锐设计竞赛·华灿奖',
    '全国三维数字化创新设计大赛',
    '中国大学生服务外包创新创业大赛',
    '中国大学生计算机设计大赛',
    '中国高校计算机大赛大数据挑战赛',
];
exports.COMPETITION_B_NATIONAL = [
    '全国高校大学日语演讲比赛',
    '中国人日语作文大赛',
    '中国大学生英语辩论赛（CUDC）',
    '中国日报社"21 世纪杯"全国英语演讲比赛',
    '"理解当代中国"全国大学生外语能力大赛（国赛）',
    '"外研社·国才杯"全国大学生英语辩论赛',
    '全国高校俄语大赛',
    '全国德语专业大学生辩论赛',
    '"意大利语桥"系列比赛',
    '全国意大利语演讲比赛',
    '全国波兰语翻译大赛',
    '哈萨克语语言文化竞赛',
    '"外教社杯"高校法语演讲比赛',
    '全国捷克语演讲比赛',
    '世界中葡翻译大赛',
    '徐日昇奖比赛',
    '泰语演讲比赛',
    'CATTI 杯全国翻译大赛',
    '韩素音国际翻译大赛',
    '未来设计师·全国高校数字艺术设计大赛（NCDA）',
    '"学创杯"全国大学生创业综合模拟演训活动',
    '全国大学生商科综合能力大赛',
    '"杰赛普"国际法模拟法庭竞赛',
    '国际刑事法院模拟法庭竞赛',
    '全国大学生海洋文化创意设计大赛',
    'CCF 大学生计算机系统与程序设计竞赛（CCSP）',
    'ICPC 国际大学生程序设计竞赛全国邀请赛',
    '全国大学生数学竞赛',
    '中国大学生程序设计竞赛（CCPC）',
    '中国高校计算机大赛-团体程序设计天梯赛（GPLT）',
    'IPv6 技术应用创新大赛科教赛道暨下一代互联网技术创新大赛',
    '大学生新媒体创意大赛',
    '中报全国模联活动',
    '中国模拟联合国大会',
    '"甲骨文杯"国际学生"我与汉字"演讲大赛',
    '中国大学生排球联赛（普通本科组）',
    '全国大学生创新年会',
];
exports.COMPETITION_B_PROVINCIAL = [
    '长安杯中国大学生日语才能演示大赛',
    '"早道杯"辽宁省大学生日语技能大赛',
    '辽沈翻译风采大赛（"辽沈最美翻译官"外语演讲大赛）',
    '中华全国日语演讲比赛（东北赛区）',
    '"理解当代中国"辽宁省大学外语能力大赛（省赛）',
    '"高教社杯"商业英语辩论大赛暨全国高校创新创业系列赛',
    '全国高校商务英语竞赛',
    '"俄罗斯文艺"文学翻译奖·全球俄汉互译大赛',
    '"哈尔滨俄语之春"中俄大学生俄语竞赛',
    '汉俄科技翻译大赛',
    '全国法语歌曲大赛',
    '全国高校法语配音大赛',
    '中法环境月法语演讲大赛',
    '"德语之星"全国高校德语演讲',
    '全国高校德语专业本科生学术创新大赛',
    '全国高校本科生德语配音大赛',
    '东北三省大学生韩国语演讲比赛',
    '"乐椿轩杯"东北三省高校韩语演讲比赛',
    '全国高校西班牙语配音大赛',
    '全国西班牙语之星演讲大赛',
    '东北三省意大利语演讲比赛',
    '全国大学生波兰语演讲比赛',
    '中国高校中葡笔译大赛',
    '全国葡萄牙语演讲比赛',
    '"东盟语言讲中国故事"短视频大赛',
    '"永旺杯"多语种全国口译大赛',
    '"云山杯"国际远程口译大赛',
    '全国（中国）高校印尼语口语大赛',
    '全国高校阿拉伯语专业学生征文大赛',
    '中阿在校大学生翻译比赛',
    '中国高校阿拉伯文书法比赛',
    '北京语言大学国际口笔译翻译大赛同传邀请赛',
    '辽宁省翻译大赛',
    '全国口译大赛',
    '上海外国语大学多语种接力同传赛',
    '杭州国际电子音乐作曲比赛',
    '"浙音"青少年艺术节民乐专场',
    '中韩国际艺术节',
    '辽宁省大中小学师生美术作品大赛',
    '辽宁省高校师生美术作品大赛',
    '中国当代大学生艺术作品年鉴大赛',
    '未来设计师·全国高校数字艺术设计大赛',
    '米兰设计周-中国高校设计学科师生优秀作品展',
    '白金创意国际大学生平面设计大赛',
    '辽宁省"强省杯"工业设计大赛',
    '"学创杯"全国大学生创业综合模拟大赛（辽宁赛区）',
    'IMA 校园管理会计大赛',
    '"贸仲杯"国际商事仲裁模拟仲裁庭辩论赛',
    '中国国际海洋模拟法庭竞赛',
    '全国大学生数字技能应用大赛"互联网+"技能应用赛',
    '全国高校商业精英挑战赛国际贸易竞赛',
    '东北地区大学生程序设计竞赛',
    '蓝桥杯全国大学生软件和信息技术大赛（国赛）',
    '辽宁省大学生程序设计竞赛',
    '百度之星程序设计大赛',
    '东北三省数学建模联赛',
    '中国大学生广告艺术节学院奖',
    '中国数据新闻大赛',
    '全国大学生全球胜任力素养大赛暨辽宁省外事外交风采大赛',
    '北京大学亚洲国际模拟联合国大会',
    '北京国际模拟联合国大会',
    '儒家经典跨语言诵读大会',
    '"外教社杯"全国高校学生跨文化能力大赛',
    '辽宁省大学生羽毛球锦标赛',
    '辽宁省"省长杯"青少年校园足球联赛',
    '中国大学生篮球联赛（本科院校组）辽宁赛区',
    '辽宁省大学生创新大赛',
    '辽宁省大学生创新年会',
    '辽宁省国际学生创新大赛',
];
exports.COMPETITION_B_MUNICIPAL = [
    '大连市"佳能杯"日语演讲比赛',
    '大连市"枫叶杯"英语演讲比赛',
    '大连市模拟联合国大会',
    '"感知中国遇见大连"来华留学生海外社交媒体影响力大赛',
    '全国啦啦操联赛',
    '大连市高校学生匹克球比赛',
    '大连市高校阳光体育冬季长跑',
];
/** 语言技能证书白名单（学院研判 2026） */
exports.CERT_LANG_ENTRIES = [
    { type: 'CERT_LANG', name: '大学英语四级（CET-4）', extra: { minScore: 425 } },
    { type: 'CERT_LANG', name: '大学英语六级（CET-6）', extra: { minScore: 425 } },
    { type: 'CERT_LANG', name: '日本语能力测试（JLPT）N2', extra: { grades: ['N2'] } },
    { type: 'CERT_LANG', name: '日本语能力测试（JLPT）N1', extra: { grades: ['N1'] } },
    { type: 'CERT_LANG', name: '英语专业四级（TEM-4）', extra: { grades: ['合格', '良好', '优秀'] } },
    { type: 'CERT_LANG', name: '英语专业八级（TEM-8）', extra: { grades: ['合格', '良好', '优秀'] } },
];
